In [1]:
import csv
import json

In [2]:
from prettytable import PrettyTable

In [3]:
import numpy as np
import pandas as pd


In [4]:
myTable = PrettyTable(["Method", "Accuracy", "Precision", "Recall","F1-Score"])

In [5]:
header = ['address','outdegree','indegree','out_amount','in_amount','net_balance','avg_out_amount','avg_in_amount','min_out_amount','min_in_amount','max_out_amount','max_in_amount','fraud']
df = pd.read_csv ('processed_data.csv')
df

address  outdegree  indegree  \
0         0xea193cb28cf6150b4cbaf0cfe7b39241e28091a7         35        34   
1         0xf5bec430576ff1b82e44ddb5a1c93f6f9d0884f3      27941    162281   
2         0xdd2a6795422100e5f2c4e30c5a6f7553e81baab9        288       290   
3         0x44f14099b8b9c60515e83a0cb1a85e14982bb091       3603     27117   
4         0x2e1809d345216aa72833ba5f2881885c2999c103          1         0   
...                                              ...        ...       ...   
14415149  0x984a0f05e7357810026809197640c2af64ff6bf2          0         1   
14415150  0x1ed25200c3006f2ee09d59b33b140f9f246e93df          0         1   
14415151  0xff8451ba9e7bf862c8682d2285ed6bae9b89821a          0         1   
14415152  0x5afe7202a1f0faf0fd77ffe308f4782e6aa0aaec          0         1   
14415153  0x1c9d943087de156c149aa53fa159a814033ff51c          0         1   

            out_amount     in_amount   net_balance  avg_out_amount  \
0             3.697097  3.683651e+00 -1.344561e-02        0.105631   
1         83040.489414  7.879216e+04 -4.248334e+03        2.971994   
2            38.550530  3.867898e+01  1.284463e-01        0.133856   
3         16524.628009  1.653075e+04  6.118371e+00        4.586352   
4             0.000000  0.000000e+00  0.000000e+00        0.000000   
...                ...           ...           ...             ...   
14415149      0.000000  4.931300e-01  4.931300e-01        0.000000   
14415150      0.000000  1.479000e+00  1.479000e+00        0.000000   
14415151      0.000000  4.700000e-11  4.700000e-11        0.000000   
14415152      0.000000  9.140000e-10  9.140000e-10        0.000000   
14415153      0.000000  1.043322e-02  1.043322e-02        0.000000   

          avg_in_amount  min_out_amount  min_in_amount  max_out_amount  \
0          1.083427e-01    4.899493e-02   5.004493e-02        0.279714   
1          4.855291e-01    2.100000e-07   0.000000e+00     1798.023000   
2          1.333758e-01    7.887910e-03   8.937910e-03        0.522101   
3          6.096082e-01    1.459961e-01   7.816789e-09     1100.000000   
4          0.000000e+00    0.000000e+00   0.000000e+00        0.000000   
...                 ...             ...            ...             ...   
14415149   4.931300e-01    0.000000e+00   4.931300e-01        0.000000   
14415150   1.479000e+00    0.000000e+00   1.479000e+00        0.000000   
14415151   4.700000e-11    0.000000e+00   4.700000e-11        0.000000   
14415152   9.140000e-10    0.000000e+00   9.140000e-10        0.000000   
14415153   1.043322e-02    0.000000e+00   1.043322e-02        0.000000   

          max_in_amount  fraud  
0          2.807642e-01      0  
1          1.703227e+03      0  
2          4.237784e-01      0  
3          7.291643e+01      0  
4          0.000000e+00      0  
...                 ...    ...  
14415149   4.931300e-01      0  
14415150   1.479000e+00      0  
14415151   4.700000e-11      0  
14415152   9.140000e-10      0  
14415153   1.043322e-02      0  

[14415154 rows x 13 columns]

In [6]:
df['fraud'].value_counts()

0    14413790
1        1364
Name: fraud, dtype: int64

In [7]:
from imblearn import under_sampling 
from imblearn import over_sampling
from imblearn.over_sampling import SMOTE

In [8]:
from sklearn import preprocessing
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

In [9]:
#RANDOM UNDERSAMPLING

from sklearn.utils import resample

# Separate the majority and minority classes
majority_class = df[df['fraud'] == 0]
minority_class = df[df['fraud'] == 1]

# Perform random undersampling on the majority class
n_samples = 25000
majority_class_undersampled = resample(majority_class,
                                       replace=False,
                                       n_samples=n_samples,
                                       random_state=42)

# Combine the majority and minority classes into a new DataFrame
df_undersampled = pd.concat([majority_class_undersampled, minority_class])

# Shuffle the new DataFrame
df_undersampled = df_undersampled.sample(frac=1, random_state=42)
df = df_undersampled
df

address  outdegree  indegree  \
8532284   0xe54c50e7ea6d265faa7b66588baab664b84e61ac          4         1   
8927706   0x0e9c06e8e3c0403f9c3081f35b83595057081e65         10         7   
437450    0x34057bc5e7c70762cc75e432ea7a4e747ebebfcc         10         7   
10197693  0x0eda007045adcce46a5ba7c5d6464910170c331c          1         1   
2582089   0xf8fab62ce66121fdd8641e568aa2f3d6b9392f01          1         1   
...                                              ...        ...       ...   
7837755   0xa7dcd6e246392eddb9a68825fba2aa946e616744          1         0   
8781264   0xd4044f491991e24d3909beec95e9eb52e6906ef6          1         1   
11039362  0x96f9a1df3c29c01d877e7822ad74a1859503c5b9          1         1   
5599874   0xe3ad5cea340a2125c372e695ae542b32c6750561          1         0   
8094089   0x7d024050224ea56d277c5a539db16957e015b3f8          6         4   

            out_amount  in_amount  net_balance  avg_out_amount  avg_in_amount  \
8532284   0.000000e+00   0.004000     0.004000    0.000000e+00       0.004000   
8927706   4.247501e-09   0.004300     0.004300    4.247501e-10       0.000614   
437450    3.959300e+01  39.597200     0.004200    3.959300e+00       5.656743   
10197693  8.950000e-03   0.010000     0.001050    8.950000e-03       0.010000   
2582089   9.866365e-02   0.098769     0.000105    9.866365e-02       0.098769   
...                ...        ...          ...             ...            ...   
7837755   9.957359e-02   0.000000    -0.099574    9.957359e-02       0.000000   
8781264   0.000000e+00   0.009145     0.009145    0.000000e+00       0.009145   
11039362  0.000000e+00   0.000200     0.000200    0.000000e+00       0.000200   
5599874   5.742415e-01   0.000000    -0.574241    5.742415e-01       0.000000   
8094089   2.050000e-09   0.020000     0.020000    3.416667e-10       0.005000   

          min_out_amount  min_in_amount  max_out_amount  max_in_amount  fraud  
8532284         0.000000   4.000000e-03    0.000000e+00       0.004000      0  
8927706         0.000000   9.587295e-11    2.494717e-09       0.002300      0  
437450          0.805000   8.000000e-01    1.918000e+01      31.195000      0  
10197693        0.008950   1.000000e-02    8.950000e-03       0.010000      0  
2582089         0.098664   9.876865e-02    9.866365e-02       0.098769      0  
...                  ...            ...             ...            ...    ...  
7837755         0.099574   0.000000e+00    9.957359e-02       0.000000      0  
8781264         0.000000   9.144557e-03    0.000000e+00       0.009145      0  
11039362        0.000000   2.000000e-04    0.000000e+00       0.000200      0  
5599874         0.574241   0.000000e+00    5.742415e-01       0.000000      0  
8094089         0.000000   5.000000e-11    1.050000e-09       0.020000      0  

[26364 rows x 13 columns]

In [10]:
df['fraud'].value_counts()

0    25000
1     1364
Name: fraud, dtype: int64

In [11]:
#  SMOTE


# Separate the input features and target variable
X = df.drop(columns=['fraud','address'])
y = df['fraud']

# Create a SMOTE object
smote = SMOTE(random_state=42)

# Resample the data using SMOTE
X_resampled, y_resampled = smote.fit_resample(X, y)

# Create a new DataFrame with the resampled data
df_resampled = pd.concat([X_resampled, y_resampled], axis=1)

df=df_resampled
df
df['fraud'].value_counts()

0    25000
1    25000
Name: fraud, dtype: int64

# NORMALISE FEATURES dont use for now

from sklearn.preprocessing import StandardScaler


# Select the columns to be normalized
cols_to_normalize = ['outdegree','indegree','out_amount','in_amount','net_balance','avg_out_amount','avg_in_amount','min_out_amount','min_in_amount','max_out_amount','max_in_amount']

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler to the selected columns
scaler.fit(df[cols_to_normalize])

# Transform the selected columns using the scaler
df[cols_to_normalize] = scaler.transform(df[cols_to_normalize])
df

In [12]:
from sklearn.metrics import classification_report, confusion_matrix,f1_score, recall_score

In [13]:
#DT


from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix,precision_score,recall_score


# Separate the input features and target variable

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a DecisionTreeClassifier object
clf = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Compute the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
precision= precision_score(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy}")
print(f"F1-score: {f1}")
print(f"Precison: {precision}")
print(f"Recall: {recall}")
myTable.add_row(["DT",accuracy,precision,recall,f1])

[[4888   83]
 [  96  206]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4971
           1       0.71      0.68      0.70       302

    accuracy                           0.97      5273
   macro avg       0.85      0.83      0.84      5273
weighted avg       0.97      0.97      0.97      5273

Accuracy: 0.9660534799924142
F1-score: 0.697123519458545
Precison: 0.71280276816609
Recall: 0.6821192052980133


In [14]:
#RF

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a RandomForestClassifier object
clf = RandomForestClassifier(n_estimators=100, random_state=21)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Compute the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
precision= precision_score(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy}")
print(f"F1-score: {f1}")
print(f"Precison: {precision}")
print(f"Recall: {recall}")
myTable.add_row(["RF",accuracy,precision,recall,f1])

[[4953   18]
 [  99  203]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4971
           1       0.92      0.67      0.78       302

    accuracy                           0.98      5273
   macro avg       0.95      0.83      0.88      5273
weighted avg       0.98      0.98      0.98      5273

Accuracy: 0.9778114925090081
F1-score: 0.7762906309751435
Precison: 0.918552036199095
Recall: 0.6721854304635762


In [15]:
#GB
from sklearn.ensemble import GradientBoostingClassifier

# Create a GradientBoostingClassifier object
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Compute the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
precision= precision_score(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy}")
print(f"F1-score: {f1}")
print(f"Precison: {precision}")
print(f"Recall: {recall}")
myTable.add_row(["GB",accuracy,precision,recall,f1])

[[4964    7]
 [ 110  192]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4971
           1       0.96      0.64      0.77       302

    accuracy                           0.98      5273
   macro avg       0.97      0.82      0.88      5273
weighted avg       0.98      0.98      0.98      5273

Accuracy: 0.9778114925090081
F1-score: 0.7664670658682635
Precison: 0.964824120603015
Recall: 0.6357615894039735


In [16]:
#KNN

from sklearn.neighbors import KNeighborsClassifier


# Create a KNeighborsClassifier object
clf = KNeighborsClassifier(n_neighbors=5)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Compute the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
precision= precision_score(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy}")
print(f"F1-score: {f1}")
print(f"Precison: {precision}")
print(f"Recall: {recall}")
myTable.add_row(["KNN",accuracy,precision,recall,f1])

[[4943   28]
 [ 115  187]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4971
           1       0.87      0.62      0.72       302

    accuracy                           0.97      5273
   macro avg       0.92      0.81      0.85      5273
weighted avg       0.97      0.97      0.97      5273

Accuracy: 0.9728807130665655
F1-score: 0.7234042553191489
Precison: 0.8697674418604651
Recall: 0.6192052980132451


/Users/adithyabalaji/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:237: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [17]:
#MLP

from sklearn.neural_network import MLPClassifier

# Create an MLPClassifier object
clf = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', solver='adam', max_iter=1000)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Compute the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
precision= precision_score(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy}")
print(f"F1-score: {f1}")
print(f"Precison: {precision}")
print(f"Recall: {recall}")
myTable.add_row(["MLP",accuracy,precision,recall,f1])

[[4911   60]
 [ 195  107]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      4971
           1       0.64      0.35      0.46       302

    accuracy                           0.95      5273
   macro avg       0.80      0.67      0.72      5273
weighted avg       0.94      0.95      0.95      5273

Accuracy: 0.951640432391428
F1-score: 0.4562899786780384
Precison: 0.6407185628742516
Recall: 0.3543046357615894


In [ ]:
#SVM

from sklearn.svm import SVC

# Create an SVM object
clf = SVC(kernel='linear')

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Compute the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall= recall_score(y_test, y_pred)
precision= precision_score(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy}")
print(f"F1-score: {f1}")
print(f"Precison: {precision}")
print(f"Recall: {recall}")
myTable.add_row(["SVM",accuracy,precision,recall,f1])

In [18]:
print(myTable)

+--------+--------------------+--------------------+--------------------+--------------------+
| Method |      Accuracy      |     Precision      |       Recall       |      F1-Score      |
+--------+--------------------+--------------------+--------------------+--------------------+
|   DT   | 0.9660534799924142 |  0.71280276816609  | 0.6821192052980133 | 0.697123519458545  |
|   RF   | 0.9778114925090081 | 0.918552036199095  | 0.6721854304635762 | 0.7762906309751435 |
|   GB   | 0.9778114925090081 | 0.964824120603015  | 0.6357615894039735 | 0.7664670658682635 |
|  KNN   | 0.9728807130665655 | 0.8697674418604651 | 0.6192052980132451 | 0.7234042553191489 |
|  MLP   | 0.951640432391428  | 0.6407185628742516 | 0.3543046357615894 | 0.4562899786780384 |
+--------+--------------------+--------------------+--------------------+--------------------+
